# Generated by Django 5.0.1 on 2026-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docutracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_email',
            field=models.EmailField(blank=True, help_text='Official email address for faculty users', max_length=254),
        ),
    ]
